export const GET_USERS = 'GET_USERS'
export const LOGIN = 'LOGIN'
export const GET_PROFILE = 'GET_PROFILE'
export const GET_TOPICS = 'GET_TOPICS'
export const GET_MESSAGE_USERS ='GET_MESSAGE_USERS'
export const GET_MYCONVO = 'GET_MYCONVO'
export const SEND_MSG ='SEND_MSG'
export const GET_ROOM = 'GET_ROOM'
export const CHANGE_DRAWER = 'CHANGE_DRAWER'

